import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/Header/Header";
import "./globals.scss";
import "@fortawesome/fontawesome-svg-core/styles.css";
import "react-phone-input-2/lib/style.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
config.autoAddCss = false;

const inter = Inter({ subsets: ["latin"] });

import StyledComponentsRegistry from "../lib/AntdRegistry";
import Footer from "@/components/Footer/Footer";
import { ConfigProvider } from "antd";
import ClientProvider from "@/utils/ClientProvider";
import VerifyAccountFloat from "@/components/VerifyAccountFloat/VerifyAccountFloat";

export const metadata: Metadata = {
  title: "Wryntal - Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <ConfigProvider
            theme={{
              token: {
                colorPrimary: "#0094ff",
                colorInfo: "#0094ff",
                colorBgBase: "#f4f6f8",
                borderRadius: 8,
                fontFamily: "Inter",
              },
              components: {
                Input: {
                  paddingInlineLG: 18,
                  controlHeightLG: 44,
                  fontSizeLG: 14,
                },
                InputNumber: {
                  paddingInline: 18,
                  paddingInlineLG: 18,
                  controlHeightLG: 44,
                  fontSizeLG: 14,
                },
                Button: {
                  paddingInlineLG: 28,
                  controlHeightLG: 44,
                  fontSizeLG: 14,
                },
                Checkbox: {
                  controlInteractiveSize: 18,
                },
                Select: {
                  paddingSM: 16,
                  fontSizeLG: 14,
                  paddingLG: 18,
                  controlHeightLG: 44,
                },
                Pagination: {
                  colorBgContainer: "rgb(255, 255, 255)",
                },
              },
            }}
          >
            <ClientProvider>
              <Header />
              {children}
              <Footer />
              <VerifyAccountFloat />
              <ToastContainer />
            </ClientProvider>
          </ConfigProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
